version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres_lab4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:


